### auth 授权码
### 第一步申请授权码(浏览器请
### 求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.xuecheng-plus.com

POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=vJWpiu&redirect_uri=http://www.wenli.com


### auth 密码
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123

###校验 jwt 令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmciXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc2NzgyNjMwLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJlNjg3N2ZmYy0yMzBlLTQ1YTgtOWRhYS1jYzYwNzQxYWYxMTYiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.nEiZdPO6DUwxTochJIlHdzn0pNFJI1bV2HtlDcML7TE
