### auth 授权码
### 第一步申请授权码(浏览器请
### 求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.xuecheng-plus.com

POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=vJWpiu&redirect_uri=http://www.wenli.com


### auth 密码
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=stu1&password=11111

###校验 jwt 令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmciXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc2NzgzNzEzLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJjODYxYjE4ZS05MDVmLTRkZTMtYjczZi0yNGY4M2QwY2MzYzgiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.Ojj1AthbhjVvFlfRmQK53m5GU7rt2wOeuVZzZHc5sms


### 查询课程
GET {{content_host}}/content/course/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmciXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc2NzgzODUxLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiIzOTU1YzM3ZC1mOGM2LTQzN2UtYmJhZC00ZjAwZWZhOTQyYmEiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.oNhZuYpwd6xFyBmKk9YN3IBK4zUPQ8uw-gK33Eh6m_4


### 通过网关访问资源服务
GET {{gateway_host}}/content/course/2
